### ISSUE TITLE
Can this be integrated to an Existing Swift project ?

### ISSUE THREAD

**Issue by thisara8** [bichenkk/ios-videocover-demo-objc#4]
This is not actually an issue, i am just wondering if anyone can help me with some information.. as this is the most simple and the best video background i saw (after googling for days) and i think i would be able to use it on my swift project (even with my very little Xcode, Swift knowledge) can someone tell me the best way to integrate this to an existing swift project? just for the landing page... or how to create this? 

Thank you

**Comment by bichenkk** [comment]
Hi, thanks for your interest!
Would you wait for an hour? I am adding the swift version of the video cover demo.

**Comment by bichenkk** [comment]
@thisara8 Hi, please find the swift version here.
https://github.com/bichenkk/ios-videocover-demo-swift
You can see how I use the av player and create a similar one for you own :)
Feel free to ask me if you have problems.

**Comment by thisara8** [comment]
@bichenkk Thank you very much for the Swift version, i am very new to Swift or Xcode, i have planed to start working on this, i believe it won't be difficult, i will definitely let you know how it goes ;) Thank you again,
